Add files via upload
nlfop/2020-2-Atom-QA-Python-A-Lvovskya pull request #2
Opened 2020-10-12 14:51 UTC by nlfop

# Домашнее задание №

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
*
*
*

2020-10-18 00:30 UTC, SK1995 requested changes, later dismissed
В целом хорошая работа, видно, что старалась, спасибо.
Очень здорово, что в тестах используется аллюр.
Но пока есть над чем поработать, отписался в комментариях, что хотелось бы изменить.

Не по коду хочется добавить пару замечаний:
- Имена файлов. Принято их давать в стиле [snake_case](https://ru.wikipedia.org/wiki/Snake_case).  Имена вроде `createcompanypage.py` очень тяжело читаются.
- В коммитах встречается много ненужных *.pyc файлов. Рекомендую настроить их игнорирование через файл .gitignore в проекте (просто добавить туда строчку. `*.pyc`).

2020-10-18 00:30 UTC, SK1995 commented on HW2/UI/fixtures.py
> +        #driver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub/',
Это наверное лучше убрать, если селеноид не подключен.
Чтобы не было лишних комментов в коде.

2020-10-18 00:30 UTC, SK1995 commented on HW2/UI/fixtures.py
> +        options.add_argument("--window-size=800,600")
А `"--window-size=800,600"` как-то в тестах используется?
Там просто дальше все равно идет вызов `driver.maximize_window()`, который разворачивает открытый браузер на весь экран. 
Поэтому думаю, что эту опцию можно убрать.

2020-10-18 00:30 UTC, SK1995 commented on HW2/UI/fixtures.py
> +@pytest.fixture(scope='function', params=['chrome', 'firefox'])
Это тоже похоже нигде не используется.
Вообще рекомендую почистить код от копипасты с лекции, чтобы не путаться потом в том, зачем это сюда было добавлено и что делает.

2020-10-18 00:30 UTC, SK1995 commented on HW2/UI/locators/basic_locators.py
> +    AUDIENCE = (By.XPATH, '/html/body/div[1]/div/div[1]/div/div/div/div[2]/ul/li[2]/a')
Здесь и дальше по коду локаторы _максимально_ непонятные :)

Уже можно не менять, но на будущее - надо стараться все-таки не использовать автосгенерированные локатры там, где это возможно. 

Это приведет к тому, что малейшее изменение верстки разломает все тесты, т. к. элементы перестанут находиться по указанным путям.

2020-10-18 00:30 UTC, SK1995 commented on HW2/UI/pages/basepage.py
> +    def go_to_password(self):
Если это `BasePage`, то метод `go_to_password` в ней явно лишний. И методы `login` и `go_to_home_page ` тоже.
Для него лучше сделать отдельный класс `LoginPage`.

Потому что сейчас от него наследуется `CreateCompanyPage`, в котором вызовы этих функций явно приведут к ошибкам, т. к. локаторов, которые используются при логине, на странице с созданием кампаний не будет.

2020-10-18 00:30 UTC, SK1995 commented on HW2/UI/pages/basepage.py
> +        self.login("anlvovskay@mail.ru", "Anastya")
Тут было бы здорово возвращать объект класса `CreateCompanyPage`. 
Тогда в тестах можно было бы строить красивые цепочки вызовов функций.

Вот так, например:
```python
class Test(BaseCase):
    def test_example(self):
        home_page = self.basepage.go_to_home_page()
        home_page.create_company()
        ...
```

Заодно можно ждать, что на странице появилась информация о залогиненном пользователе.
Тогда в тестах часть `sleep()` тоже уйдет. 
Ожидать элемент можно вот так, например
```python
    def wait_until_visible(self, timeout=5) -> WebElement:
        return self.wait(timeout=timeout).until(
            EC.visibility_of_element_located((By.XPATH, '//div[@title="<ИМЯ_ПОЛЬЗОВАТЕЛЯ>"]')))
```

Сейчас можно уже не исправлять, но на будущее стоит помнить об этом.

2020-10-18 00:30 UTC, SK1995 commented on HW2/UI/pages/createcompanypage.py
> +        pyautogui.write('C:\\Users\\ulvov\\Pictures\\selenium IDE.png')
Так нельзя делать ни в коем случае. Вот несколько причин:

1) Самая банальная - у меня нет этого файла. Он должен лежать в репозитории с автотестами и заливаться из него.
2) Будет работать только на винде, т. к. путь специфичен для системы. Лучше положить файл в каталог с автотестами, после чего прямо из кода его искать. Например вот так:
```python
# Подразумевается, что картинка лежит в том же каталоге, что и текущий файл.
# Но вообще ее можно в любой каталог проекта положить, и рассчитать путь относительно текущего файла аналогичным способом
curr_file_path = os.path.abspath(__file__)
curr_dir = os.path.dirname(curr_file_path)
image_path = os.path.join(curr_dir, 'image.png')
```

3) Модуль pyautogui не нужен совсем. Во-первых, на python 3.8 он просто не работает. Во-вторых, у селениума есть все, чтобы загрузить картингу в input. Вот [пример](https://stackoverflow.com/a/10472542).
То есть, просто вместо вот этого
```python
photo_download = self.find(self.locators.PHOTO)
        photo_download.click()
        time.sleep(2)
        pyautogui.write('C:\\Users\\ulvov\\Pictures\\selenium IDE.png')
        pyautogui.press('enter')
        self.find(self.locators.ADD_PHOTO).click()
```
делать вот так:
```python
self.find(self.locators.ADD_PHOTO).send_keys("<image_path>/image.png")
```

Тут я виноват, что об этом на лекции не рассказал, прошу прощения :)

2020-11-06 11:16 UTC, snicks92 approved these changes

2020-11-06 11:16 UTC, merged